### ISSUE TITLE
Images Not Responsive On Mobile View

### ISSUE THREAD

**Issue by AshleyPoole** [shropshiredevnet/shropshiredevnet.github.io#4]
When scaling down the net image isn't being responsive as I think it should be... See images...

<img width="1024" alt="screen shot 2015-10-02 at 08 39 04" src="https://cloud.githubusercontent.com/assets/3891630/10241503/6a85b344-68e1-11e5-82c5-8854be3d5aac.png">
<img width="524" alt="screen shot 2015-10-02 at 08 38 38" src="https://cloud.githubusercontent.com/assets/3891630/10241504/6bad6b72-68e1-11e5-8c8e-541942a3e6b8.png">

**Comment by magicweasel** [comment]
I've sorted this a bit in the latest PR

**Comment by AshleyPoole** [comment]
Confirmed, working great.
